// Code generated by gen-ast-types. DO NOT EDIT.

package ast

import (
	"errors"
	"github.com/nanmu42/bluelox/token"
)

type Expression interface {
	Accept(visitor ExprVisitor) (result interface{}, err error)
}

type Statement interface {
	Accept(visitor StmtVisitor) (err error)
}

type ExprVisitor interface {
	VisitBinaryExpr(v *BinaryExpr) (result interface{}, err error)
	VisitGroupingExpr(v *GroupingExpr) (result interface{}, err error)
	VisitLiteralExpr(v *LiteralExpr) (result interface{}, err error)
	VisitUnaryExpr(v *UnaryExpr) (result interface{}, err error)
}

type StubExprVisitor struct{}

var _ ExprVisitor = StubExprVisitor{}

func (s StubExprVisitor) VisitBinaryExpr(_ *BinaryExpr) (interface{}, error) {
	return nil, errors.New("visit func for BinaryExpr is not implemented")
}

func (s StubExprVisitor) VisitGroupingExpr(_ *GroupingExpr) (interface{}, error) {
	return nil, errors.New("visit func for GroupingExpr is not implemented")
}

func (s StubExprVisitor) VisitLiteralExpr(_ *LiteralExpr) (interface{}, error) {
	return nil, errors.New("visit func for LiteralExpr is not implemented")
}

func (s StubExprVisitor) VisitUnaryExpr(_ *UnaryExpr) (interface{}, error) {
	return nil, errors.New("visit func for UnaryExpr is not implemented")
}

type BinaryExpr struct {
	Left     Expression
	Operator *token.Token
	Right    Expression
}

var _ Expression = (*BinaryExpr)(nil)

func (b *BinaryExpr) Accept(visitor ExprVisitor) (result interface{}, err error) {
	return visitor.VisitBinaryExpr(b)
}

type GroupingExpr struct {
	Expr Expression
}

var _ Expression = (*GroupingExpr)(nil)

func (b *GroupingExpr) Accept(visitor ExprVisitor) (result interface{}, err error) {
	return visitor.VisitGroupingExpr(b)
}

type LiteralExpr struct {
	Value interface{}
}

var _ Expression = (*LiteralExpr)(nil)

func (b *LiteralExpr) Accept(visitor ExprVisitor) (result interface{}, err error) {
	return visitor.VisitLiteralExpr(b)
}

type UnaryExpr struct {
	Operator *token.Token
	Right    Expression
}

var _ Expression = (*UnaryExpr)(nil)

func (b *UnaryExpr) Accept(visitor ExprVisitor) (result interface{}, err error) {
	return visitor.VisitUnaryExpr(b)
}

type StmtVisitor interface {
	VisitExprStmt(v *ExprStmt) (err error)
	VisitPrintStmt(v *PrintStmt) (err error)
}

type StubStmtVisitor struct{}

var _ ExprVisitor = StubExprVisitor{}

func (s StubExprVisitor) VisitExprStmt(_ *ExprStmt) error {
	return errors.New("visit func for ExprStmt is not implemented")
}

func (s StubExprVisitor) VisitPrintStmt(_ *PrintStmt) error {
	return errors.New("visit func for PrintStmt is not implemented")
}

type ExprStmt struct {
	Expr Expression
}

var _ Statement = (*ExprStmt)(nil)

func (b *ExprStmt) Accept(visitor StmtVisitor) (err error) {
	return visitor.VisitExprStmt(b)
}

type PrintStmt struct {
	Expr Expression
}

var _ Statement = (*PrintStmt)(nil)

func (b *PrintStmt) Accept(visitor StmtVisitor) (err error) {
	return visitor.VisitPrintStmt(b)
}
